### ISSUE TITLE
Timeout parameter doesn't work when retry is configured

### ISSUE THREAD

**Issue by geigerj** [googleapis/gax-ruby#71] opened 2017-06-02 18:52 UTC
Originally reported by @frankyn

### What

Setting CallOptions timeout does nothing when the RPC is configured to retry.

### To reproduce

```
video_service_client = Google::Cloud::VideoIntelligence::V1beta1::VideoIntelligenceServiceClient.new
features             = [Google::Cloud::Videointelligence::V1beta1::Feature::LABEL_DETECTION]                                                                                           
options = Google::Gax::CallOptions.new(timeout: 60)
path = "gs://cloudmleap/video/next/volleyball_court.mp4"
                                                                                                                  
operation = video_service_client.annotate_video(path, features, options: options) do |op|
  ...
end
```

### Expected behavior

The call retries with an initial timeout of 60s.

### Observed behavior

The call fails with "INVALID_ARGUMENT" due to an initial timeout of 19s; the configured timeout is ignored. It is possible to change the timeout only by manually configuring the full backoff settings.

**Comment by eoogbe** [comment] 2017-08-10 00:38
I'm getting a different error:
```
GaxError Exception occurred in retry method that was not classified as transient, caused by
7:Google Cloud Video Intelligence API has not been used in project usable-auth-library before or it is
disabled. Enable it by visiting
https://console.developers.google.com/apis/api/videointelligence.googleapis.com/overview?project=usable-auth-library
then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our
systems and retry. (Google::Gax::RetryError)
```

**Comment by geigerj** [comment] 2017-08-10 05:52
@eoogbe Try using the project `gapic-test`, which should have the API enabled already.

**Comment by geigerj** [comment] 2017-08-10 05:57
Can you follow up with @vchudnov-g about the `usable-

**Comment by eoogbe** [comment] 2017-08-10 18:50
It's maxxed on keys. I can't create a new one.

**Comment by eoogbe** [comment] 2017-08-10 19:08
Thank you for your bug report. Based on its current description, we are unable to reproduce it. If you are still experiencing this issue and are reasonably certain that it is a bug, please feel free to re-open this issue with additional information to help us reproduce it.

**Comment by geigerj** [comment] 2017-08-10 19:15
@eoogbe we've updated the timeout configuration since the original bug report; are you sure you're not just seeing that? I'd be surprised if the root cause was fixed in GAX because AFAIK no work has been done there. Happy to sync offline in more detail.

**Comment by geigerj** [comment] 2017-08-10 20:15
I've confirmed the bug still exists with a print debug https://github.com/geigerj/gax-ruby/commit/248eab99ee2a25c7c3348a4b66f0174f3e594ef0, even though the configuration has changed for the specific video-intelligence case. I am fairly certain the retry settings are overriding the timeout parameter, even though the expect behavior is for the method parameters to override the configuration.

@eoogbe PTAL.

**Comment by eoogbe** [comment] 2017-08-10 21:50
The docs say:
```
# @param timeout [Numeric] The client-side timeout for API calls. This
#   parameter is ignored for retrying calls.
```

I don't think the timeout parameter is supposed to affect retry. I was able to test setting the `retry_options` keyword, which does change the timeout for retry.

Closing as works as intended.

**Comment by geigerj** [comment] 2017-08-10 21:56
This is a pretty big usability issue as is -- I don't think we can reasonably expect anyone to pass a full retry configuration as a parameter to a retrying call just to change the initial timeout parameter, and this is not an advanced use case. Let's change the behavior so that the timeout param is not ignored for retrying calls, but instead overrides the initial_rpc_timeout (and the max_rpc_timeout/total_timeout if either of those values is less than the explicitly specified timeout param).

**Comment by geigerj** [comment] 2017-08-10 22:09
Also, FWIW, the type of the `options` parameter is `CallOptions`, not `CallSettings`, which does not have the documentation you quoted. I am less concerned about `CallSettings`, because we don't expect most users to interact with it directly.

**Comment by jiren** [comment] 2018-04-30 19:04
This is an issue with `retry_codes` with empty array. If `retry_codes` is empty array and  `timeout` param is passed using call option then it is executing retry instead of timeout

 i.e here `non_idempotent` codes is empty so it should try with timeout options not using retryable.
 https://github.com/googleapis/gax-ruby/blob/ed625890bb75e063bd466d5b4b084657721962c9/lib/google/gax/settings.rb#L85-L87

https://github.com/googleapis/gax-ruby/blob/ed625890bb75e063bd466d5b4b084657721962c9/lib/google/gax/api_callable.rb#L252
https://github.com/googleapis/gax-ruby/blob/ed625890bb75e063bd466d5b4b084657721962c9/lib/google/gax/settings.rb#L85-L87

Need to check empty
```ruby
def retry_codes?
   @retry_options && @retry_options.retry_codes && !@retry_options.retry_codes.empty?
end
```

**Comment by lukesneeringer** [comment] 2018-10-08 15:47
This still seems to be in progress.
(Replying here to bring the issue back into compliance.)

**Comment by alex-lange** [comment] 2019-03-22 20:44
Hi, Has there been any updates to this issue re: `retry_codes` being an empty array?  The comments specifically say that the `RetryOptions#retry_codes` is an Array, so I believe this is an actual bug that is treating an empty array like nil (`!!nil` is `false` but `!![]` is `true`).

I think something like this should fix it:
```
def retry_codes?
   @retry_options && @retry_options.retry_codes.any?
end
```

Not sure how this repository works -- I am happy to open a PR for this!

**Comment by jbolinger** [comment] 2019-03-22 21:29
Hi @alex-lange we'd be happy to review a PR if you'd like to take a shot a fixing this. Let us know if we can help.

**Closed** 2019-04-10 17:47 UTC
Labels: :rotating_light:, priority: p2, type: feature request
